<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ScsPrefab</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ScsResource\ScsResource.csproj" />
    <ProjectReference Include="..\ScsSii\ScsSii.csproj" />
    <ProjectReference Include="..\ScsDefinitions\ScsDefinitions.csproj" />
  </ItemGroup>
</Project>
