<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>map-inspector</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\map-compiler\src\ScsValidation\ScsValidation.csproj" />
    <ProjectReference Include="..\..\..\map-compiler\src\ScsGraph\ScsGraph.csproj" />
    <ProjectReference Include="..\..\..\map-compiler\src\ScsVectorTiles\ScsVectorTiles.csproj" />
    <ProjectReference Include="..\..\..\map-compiler\src\ScsSector\ScsSector.csproj" />
    <ProjectReference Include="..\..\..\map-compiler\src\ScsResource\ScsResource.csproj" />
    <ProjectReference Include="..\..\..\map-compiler\src\ScsDefinitions\ScsDefinitions.csproj" />
    <ProjectReference Include="..\..\..\map-compiler\src\ScsPrefab\ScsPrefab.csproj" />
    <ProjectReference Include="..\..\..\map-compiler\src\ScsMapModel\ScsMapModel.csproj" />
    <ProjectReference Include="..\..\..\map-compiler\src\ScsGraph\ScsGraph.csproj" />
    <ProjectReference Include="..\..\..\map-compiler\src\ScsVectorTiles\ScsVectorTiles.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
  </ItemGroup>

</Project>
